package exceptionHandlingDemo;

import java.util.Scanner;

public class ExceptionExample {

	public static void main(String[] args) {
		int a,b,res;
		
		Scanner sc= new Scanner(System.in);
		System.out.println("Enter first number");
		a= sc.nextInt();
		
		System.out.println("Enter second number");
		b= sc.nextInt();
		
		try
		{
			res= a/b;
			System.out.println("the result is:" + res);
		}
		catch(ArithmeticException e )
		{
			System.out.println("we cannot divide:"+ e);
		}
		
			System.out.println("programme is terminated");	

	}

}
